# Generated by Django 4.1.4 on 2022-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_pn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
