# Generated by Django 4.1.4 on 2022-12-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_product_vendor_pn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='column',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='row',
            field=models.CharField(max_length=4),
        ),
    ]
